refator: `router` [not tested yet]
gnoswap-labs/gnoswap pull request #103
Opened 2023-11-29 07:31 UTC by notJoon

WIP: The refactoring is done. But I can't run the test for now, so I'll have to check it later.

2023-11-30 03:31 UTC, r3v4s commented
could you make it draft pr if it isn't ready yet

2023-12-04 00:53 UTC, notJoon commented
> @notJoon Do we need left work for this? or is it ready for review?

I'll wrap up today

2023-12-04 06:43 UTC, r3v4s commented on router/router.gno
> +		toSwap := amountSpecified / bigInt(100) * bigInt(quote)
don't change type.
`bigInt` doesn't exist, it should be `bigint`

2023-12-04 06:47 UTC, r3v4s requested changes
check comment

2023-12-05 07:12 UTC, closed without merging