WIP: Update Docs and Rerfactor Router Realm
gnoswap-labs/gnoswap pull request #297
Opened 2024-07-30 03:18 UTC by notJoon

# Description

- Reduce thje complexity of `SwapRoute` (complexity score: 24 -> under 10)

2024-07-30 04:10 UTC, dongwon8247 reviewed
Docs seem to be improved a lot, but please double check with @r3v4s if this change doesn't effect to the actual logic. Otherwise good to go!

2024-07-30 04:35 UTC, r3v4s commented on router/router.gno
> +	userNewWugnotBalance := wugnot.BalanceOf(a2u(std.GetOrigCaller()))
lint problem, I think

2024-07-30 04:37 UTC, r3v4s requested changes
tests fails on my local env. Please check from your env

2024-08-01 05:48 UTC, notJoon commented on router/router.gno
> +	userNewWugnotBalance := wugnot.BalanceOf(a2u(std.GetOrigCaller()))
https://github.com/gnoswap-labs/gnoswap/pull/297/commits/d034004817c79830272c0af01a37a3496f4bbdd2

2024-08-01 05:49 UTC, notJoon commented
> tests fails on my local env. Please check from your env

fixed https://github.com/gnoswap-labs/gnoswap/pull/297/commits/4434c47bb7ee4cb96e5cb5833d5a6249c8d0cc42

2024-08-02 03:22 UTC, r3v4s approved these changes
IMHO, high change of conflict if you fix ongoing position constructor issue.

2024-08-05 10:29 UTC, r3v4s approved these changes

2024-08-05 10:29 UTC, r3v4s commented on router/router.gno
> +		return multiSwap(*sp, 0, numHops, route) // iterate here
```suggestion
		return multiSwap(swapParams, 0, numHops, route) // iterate here
```

2024-08-05 10:50 UTC, r3v4s approved these changes

2024-08-05 11:20 UTC, dongwon8247 approved these changes

2024-08-05 11:20 UTC, merged