GSW-1425 refactor staker reward calculation
gnoswap-labs/gnoswap pull request #322
Opened 2024-08-13 10:30 UTC by r3v4s

wip //

refactor logic to reduce memory usage

2024-08-14 07:05 UTC, notJoon approved these changes

2024-08-15 11:29 UTC, dongwon8247 requested changes
Request a review meeting with me before merging this

2024-08-19 00:58 UTC, notJoon requested changes

2024-08-19 00:58 UTC, notJoon commented on staker/tier_ratio.gno
> +	}
```suggestion
	if numTier1 <= 0 {
		panic(ufmt.Sprintf("[STAKER] tier_ratio.gno__listTierRatio() || at least 1 of numTier1 need(%d), [numTier2:(%d), numTier3:(%d)]", numTier1, numTier2, numTier3))
	}
	
	hasTier2 := numTier2 > 0
	hasTier3 := numTier3 > 0

	switch {
	case !hasTier2 && !hasTier3:
		return 100, 0, 0
	case !hasTier2 && hasTier3:
		return 80, 0, 20
	case hasTier2 && !hasTier3:
		return 70, 30, 0
	case hasTier2 && hasTier3:
		return 50, 30, 20
	}
```

2024-08-19 05:00 UTC, dongwon8247 submitted a review, later dismissed

2024-08-19 05:45 UTC, notJoon approved these changes

2024-08-19 06:18 UTC, dongwon8247 approved these changes

2024-08-19 06:18 UTC, merged