GSW-1697 feat: distribute project pool reward if it has at least one deposit
gnoswap-labs/gnoswap pull request #356
Opened 2024-10-20 07:57 UTC by r3v4s

## feat
1. each project's pool reward should be (calculated and) distributed if it has at least one deposit

2024-10-20 14:06 UTC, onlyhyde requested changes

2024-10-21 03:22 UTC, r3v4s commented on launchpad/launchpad_deposit.gno
> +	if tier.totalParticipant == 1 {
44ee1c3c26a984fe048bcc4aa42b1d6df8a1f8f0

2024-10-21 03:37 UTC, onlyhyde approved these changes

2024-10-21 03:59 UTC, notJoon approved these changes

2024-10-21 03:59 UTC, merged