refactor, test(pool): Change `updatePosition` param
gnoswap-labs/gnoswap pull request #400
Opened 2024-11-22 08:50 UTC by notJoon

# Description

- Change `updatePosition` function's parameter to only take `ModifyPositionParams` type
- Add unit test for `modifyPosition`. this test covers both `update` and `modify` function

2024-11-22 10:40 UTC, onlyhyde approved these changes

2024-11-25 00:27 UTC, onlyhyde submitted a review, later dismissed

2024-11-28 12:35 UTC, r3v4s approved these changes

2024-12-01 08:58 UTC, dongwon8247 requested changes

2024-12-01 08:58 UTC, dongwon8247 commented on pool/position_modify.gno
Can you improve the nested if-else lines? Let's address them and avoid using it for better readability.

2024-12-01 08:58 UTC, dongwon8247 commented on pool/position_modify.gno
>  func (pool *Pool) modifyPosition(params ModifyPositionParams) (PositionInfo, *i256.Int, *i256.Int) {
This func should be simply about updating position. You can divide calculateTokenDeltas into another function.

2024-12-01 09:00 UTC, dongwon8247 commented on pool/position_modify.gno
Checked you already did this in #402. Great job.

2024-12-01 09:00 UTC, dongwon8247 commented on pool/position_modify.gno
>  func (pool *Pool) modifyPosition(params ModifyPositionParams) (PositionInfo, *i256.Int, *i256.Int) {
Checked you already did this in #402. Great job.

2024-12-01 09:01 UTC, dongwon8247 approved these changes

2024-12-02 01:01 UTC, merged