GSW-1838 refactor: token_register
gnoswap-labs/gnoswap pull request #409
Opened 2024-11-29 08:33 UTC by r3v4s

## refactor
1. replace `map` to `avl` for registered token list with its interface

2. more testcases

2024-12-01 15:43 UTC, dongwon8247 requested changes
Is this file necessary? 
Remove all parts related to gnoswap-labs/grc20-register, replace it with https://github.com/gnolang/gno/pull/3135.

2024-12-01 15:43 UTC, dongwon8247 commented on staker/token_register.gno
>  		panic(addDetailToError(
Avoid using panic for general errors. Return errors instead

2024-12-01 15:43 UTC, dongwon8247 commented on staker/token_register.gno
>  	locked     = false // mutex
global variables?

2024-12-01 15:43 UTC, dongwon8247 commented on staker/token_register.gno
>  	pkgPath = handleNative(pkgPath)
`handleNative` is being called multiple times overall. Make sure it's called only once where only needed.

2024-12-01 15:43 UTC, dongwon8247 commented on staker/token_register.gno
> +	return itoken.(GRC20Interface)
There should be checks. Add type assertions with error handling.

2024-12-01 15:43 UTC, dongwon8247 commented on staker/token_register.gno
>  		panic(addDetailToError(
This and dealing with global variables go the same for your other ongoing refactor work, including opened PRs. Address them.

2024-12-02 08:12 UTC, r3v4s commented
changing to draft
- new pr will be made to support grc20reg from gno
- if grc20reg works fine, this pr will be closed.

2024-12-06 10:13 UTC, r3v4s commented
grc20reg has been merged into gnolang/gno master, and it works fine with current gnoswap. Therfore closing this.

2024-12-06 10:13 UTC, closed without merging