GSW-1838 refactor: use grc20reg
gnoswap-labs/gnoswap pull request #414
Opened 2024-12-02 10:50 UTC by r3v4s

## refactor
1. use gno's `grc20reg` realm to support dynamic token in pool.
> it completely replaces previous `token_register.gno`

### FYI
this pr SHOULD BE MERGE AFTER #413

2024-12-03 02:29 UTC, notJoon submitted a review, later dismissed

2024-12-10 07:24 UTC, dongwon8247 commented
Can you check CI?

2024-12-10 10:32 UTC, onlyhyde requested changes
The 5 issues found by sonarcloud are issues, please refrain from duplicate code, hardcoding. Please include a fix commit

2024-12-10 10:45 UTC, notJoon approved these changes

2024-12-11 04:29 UTC, onlyhyde approved these changes

2024-12-11 04:31 UTC, notJoon approved these changes

2024-12-11 04:31 UTC, merged