GSW-1838 refactor: protocol fee withdrawa
gnoswap-labs/gnoswap pull request #418
Opened 2024-12-04 02:57 UTC by onlyhyde

- This commit use origin admin address (g1lmvrrrr4er2us84h2732sru76c9zl2nvknha8c)
- Some of token_register.gno code are modified (remove locked variable)
- Re-entry attacks are not possible in GNO, so the locked flag is removed. Also, due to changes in the grc20 spec, a panic may occur in the grc20 contract code, in which case the locked flag is not changed to false and terminated, locking the state value.

2024-12-04 06:04 UTC, notJoon requested changes
left some minor fix. LGTM 👍

2024-12-04 06:04 UTC, notJoon commented on pool/_helper_test.gno
> +	_amount1Min string, // *u256.Uint
need to remove prefix

```suggestion
	amount0Desired string, // *u256.Uint
	amount1Desired string, // *u256.Uint
	amount0Min string, // *u256.Uint
	amount1Min string, // *u256.Uint
```

2024-12-04 06:04 UTC, notJoon commented on pool/_helper_test.gno
> +		_amount1Min,
```suggestion
		amount0Desired,
		amount1Desired,
		amount0Min,
		amount1Min,
```

2024-12-04 06:27 UTC, r3v4s commented on pool/_helper_test.gno
> +		("1000"),
```suggestion
		"1000",
```

I don't think we need bracket

2024-12-04 06:29 UTC, r3v4s commented on pool/_helper_test.gno
> +	std.TestIssueCoins(addr, std.Coins{{denom, int64(amount)}})
seems like minting twice

2024-12-04 06:30 UTC, r3v4s commented on pool/_helper_test.gno
> +	wugnotAddr := std.DerivePkgAddr(consts.WRAPPED_WUGNOT)
this addr is defined in r/gnoswap/v1/const

2024-12-05 07:01 UTC, r3v4s approved these changes

2024-12-05 07:58 UTC, r3v4s commented
@onlyhyde I think admin address needs to be updated.

2024-12-05 08:00 UTC, merged