GSW-1838 refactor: use avl.Tree
gnoswap-labs/gnoswap pull request #430
Opened 2024-12-10 08:28 UTC by r3v4s

## refactor
1. use `avl.Tree` instead of `map`
- currently `map` has issue with processing pointer value as key

2024-12-10 09:14 UTC, notJoon approved these changes
👍

2024-12-15 12:53 UTC, onlyhyde requested changes
The base code of the current pr is too old; the application of avl.Tree should be applied from the modernized pool code. Needs to be updated

2024-12-16 03:36 UTC, r3v4s commented on pool/tick_bitmap.gno
> +	}
a926b6c2679cea8f6c3eae92ebaa04613b43c1a9

2024-12-17 01:48 UTC, notJoon submitted a review, later dismissed

2024-12-19 01:12 UTC, onlyhyde approved these changes

2024-12-19 01:12 UTC, notJoon approved these changes

2024-12-19 01:13 UTC, merged