GSW-1839 refactor: use avl.Tree in position
gnoswap-labs/gnoswap pull request #440
Opened 2024-12-16 06:45 UTC by r3v4s

## refactor
1. use `avl.Tree` instead of map
- kept `unit64` type for tokenId (no need to use seqid type for it)

2024-12-17 02:44 UTC, notJoon requested changes
It looks good. I added some comments for the documentation things, please check them.

2024-12-17 02:49 UTC, dongwon8247 commented on position/position.gno
> +	removePosition(tokenId)
fyi - we're removing the `file_func name` in the error/panic message like `position.gno__burnNFT()` here.

2024-12-17 11:02 UTC, r3v4s commented on position/position.gno
> +		// TODO:
oh sorry, missed it.
It was meant to add new error type for hard coded error string
34e10148d280714a5902fe384923c02f0ecba81d

2024-12-17 11:02 UTC, r3v4s commented on position/position.gno
> +	removePosition(tokenId)
removed unused function
removed `filename__function()` template in all error message string

529fd2fedde9d10f1b73359533825f152c339900

2024-12-17 11:04 UTC, notJoon submitted a review, later dismissed
LGTM 👍

2024-12-20 08:21 UTC, onlyhyde approved these changes

2024-12-20 08:22 UTC, notJoon approved these changes

2024-12-20 08:23 UTC, merged