GSW-1668 feat: use grc20reg to support multiple grc20 tokens
gnoswap-labs/gnoswap pull request #452
Opened 2024-12-26 12:13 UTC by r3v4s

## feat
1. use `grc20reg` realm instead previous token_register pattern to support grc20 tokens

2024-12-26 12:18 UTC, notJoon requested changes
LGTM. I left some comments

2024-12-26 12:18 UTC, notJoon commented on _deploy/r/gnoswap/common/grc20reg_helper.gno
> +	re := regexp.MustCompile(`\[gno\.land/r/[^\]]+\]`)
this regex must be a global variable

2024-12-26 12:18 UTC, notJoon commented on _deploy/r/gnoswap/common/grc20reg_helper.gno
> +	tokenPaths := []string{}
here, you can pre-allocate capacity.

```suggestion
	tokenPaths := make([]string, 0, len(matches))
```

2024-12-26 12:22 UTC, notJoon approved these changes
👍 👍

2024-12-27 06:34 UTC, onlyhyde approved these changes

2024-12-27 06:34 UTC, merged