GSW-569 feat: get `quotes` as string parameters
gnoswap-labs/gnoswap pull request #96
Opened 2023-11-20 05:41 UTC by r3v4s

- router path will be calculated from off-chain
- therefore, some of router contract parameters need change its type to primitive

2023-11-20 08:05 UTC, notJoon requested changes

2023-11-20 08:08 UTC, notJoon commented
Everything else seems to be fine 👍

2023-11-20 08:18 UTC, r3v4s commented on router/_RPC_call.gno
>  }
@notJoon like your suggestion with `handleMultiSwap` helper.

About the distinct type `SwapType`, even it has underlying string type, outer will be `SwapType` which isn't primitive. I'm not sure if user can call function(with gnokey or adena) that takes parameter other than primitive type.


I'll do some test and if it fails, will only merge `handleMultiswap`

2023-11-20 08:43 UTC, r3v4s commented on router/_RPC_call.gno
>  }
@notJoon SwapType looking GOOD.
```
# test that the example packages directory is loaded and usable.

## start a new node
gnoland start

gnokey maketx addpkg -pkgdir $WORK -pkgpath gno.land/r/primi -gas-fee 1000000ugnot -gas-wanted 2000000 -broadcast -chainid=tendermint_test test1
stdout OK!

## execute OrigInc
gnokey maketx call -pkgpath gno.land/r/primi -func OrigInc -args 123 -gas-fee 1000000ugnot -gas-wanted 2000000 -broadcast -chainid=tendermint_test test1
stdout '(123 int)'

## execute MyInc
gnokey maketx call -pkgpath gno.land/r/primi -func MyInc -args 456 -gas-fee 1000000ugnot -gas-wanted 2000000 -broadcast -chainid=tendermint_test test1
stdout '(456 gno.land/r/primi.myInt)'

## execute OrigString
gnokey maketx call -pkgpath gno.land/r/primi -func OrigString -args "qwe" -gas-fee 1000000ugnot -gas-wanted 2000000 -broadcast -chainid=tendermint_test test1
stdout 'qwe'

## execute MyString
gnokey maketx call -pkgpath gno.land/r/primi -func MyString -args "zxc" -gas-fee 1000000ugnot -gas-wanted 2000000 -broadcast -chainid=tendermint_test test1
stdout 'zxc'

-- gno.mod --
module gno.land/r/primi

-- primi.gno --
package primi

type myInt int
type myString string

func OrigInc(x int) int {
	println("orig x is:", x)
	return x
}

func MyInc(x myInt) myInt {
	println("my x is:", x)
	return x
}

func OrigString(s string) string {
	println("orig string is:", s)
	return s
}

func MyString(s myString) myString {
	println("my string is:", s)
	return s
}
```

2023-11-20 09:01 UTC, r3v4s commented on router/_RPC_call.gno
>  }
@notJoon unfortunately, we can pass `ExactIn` as typed parameter(not value parameter).
So swap type has to stay in old way ( handle*Swap is commited )

2023-11-21 07:08 UTC, notJoon approved these changes

2023-11-21 07:08 UTC, merged